/** Emoji lookup for pantry products — keyword first, category as fallback. */

const CATEGORY_EMOJI: Record<string, string> = {
  Dairy: "🥛",
  Fruits: "🍎",
  Vegetables: "🥦",
  Produce: "🥬",
  "Meat & Seafood": "🍗",
  Bakery: "🍞",
  Frozen: "🧊",
  Beverages: "🥤",
  "Grains & Pasta": "🌾",
  Snacks: "🍪",
  Condiments: "🧂",
  Spices: "🌶️",
  Other: "🛒",
};

/** Longest keyword wins, so "ice cream" beats "ice". */
const KEYWORD_EMOJI: [string, string][] = [
  ["ice cream", "🍨"],
  ["olive oil", "🫒"],
  ["cooking oil", "🛢️"],
  ["peanut butter", "🥜"],
  ["green chilli", "🌶️"],
  ["bell pepper", "🫑"],
  ["capsicum", "🫑"],
  ["sweet lime", "🍊"],
  ["cheese", "🧀"],
  ["paneer", "🧀"],
  ["butter", "🧈"],
  ["ghee", "🫙"],
  ["milk", "🥛"],
  ["curd", "🥣"],
  ["dahi", "🥣"],
  ["yogurt", "🥣"],
  ["lassi", "🥤"],
  ["buttermilk", "🥛"],
  ["cream", "🍦"],
  ["egg", "🥚"],
  ["banana", "🍌"],
  ["apple", "🍎"],
  ["orange", "🍊"],
  ["mango", "🥭"],
  ["grape", "🍇"],
  ["papaya", "🍈"],
  ["melon", "🍉"],
  ["pomegranate", "🍎"],
  ["guava", "🍐"],
  ["pear", "🍐"],
  ["pineapple", "🍍"],
  ["strawberr", "🍓"],
  ["blueberr", "🫐"],
  ["kiwi", "🥝"],
  ["lemon", "🍋"],
  ["lime", "🍋"],
  ["coconut", "🥥"],
  ["cherry", "🍒"],
  ["peach", "🍑"],
  ["avocado", "🥑"],
  ["date", "🌴"],
  ["tomato", "🍅"],
  ["onion", "🧅"],
  ["potato", "🥔"],
  ["arbi", "🥔"],
  ["arvi", "🥔"],
  ["arabi", "🥔"],
  ["taro", "🥔"],
  ["colocasia", "🥔"],
  ["yam", "🍠"],
  ["jimikand", "🍠"],
  ["suran", "🍠"],
  ["garlic", "🧄"],
  ["lehsun", "🧄"],
  ["lahsun", "🧄"],
  ["ginger", "🫚"],
  ["carrot", "🥕"],
  ["cucumber", "🥒"],
  ["brinjal", "🍆"],
  ["eggplant", "🍆"],
  ["spinach", "🥬"],
  ["lettuce", "🥬"],
  ["cabbage", "🥬"],
  ["coriander", "🌿"],
  ["mint", "🌿"],
  ["curry leaf", "🌿"],
  ["broccoli", "🥦"],
  ["cauliflower", "🥦"],
  ["corn", "🌽"],
  ["peas", "🫛"],
  ["beans", "🫘"],
  ["mushroom", "🍄"],
  ["pumpkin", "🎃"],
  ["chilli", "🌶️"],
  ["chili", "🌶️"],
  ["pepper", "🌶️"],
  ["chicken", "🍗"],
  ["mutton", "🥩"],
  ["lamb", "🥩"],
  ["beef", "🥩"],
  ["pork", "🥓"],
  ["bacon", "🥓"],
  ["sausage", "🌭"],
  ["fish", "🐟"],
  ["prawn", "🦐"],
  ["shrimp", "🦐"],
  ["crab", "🦀"],
  ["bread", "🍞"],
  ["bun", "🍔"],
  ["pav", "🍞"],
  ["croissant", "🥐"],
  ["cake", "🍰"],
  ["pastry", "🧁"],
  ["muffin", "🧁"],
  ["cookie", "🍪"],
  ["biscuit", "🍪"],
  ["rusk", "🍞"],
  ["chapati", "🫓"],
  ["roti", "🫓"],
  ["paratha", "🫓"],
  ["naan", "🫓"],
  ["pizza", "🍕"],
  ["rice", "🍚"],
  ["pasta", "🍝"],
  ["noodle", "🍜"],
  ["macaroni", "🍝"],
  ["atta", "🌾"],
  ["flour", "🌾"],
  ["maida", "🌾"],
  ["oats", "🥣"],
  ["poha", "🍚"],
  ["suji", "🌾"],
  ["rava", "🌾"],
  ["besan", "🌾"],
  ["dal", "🫘"],
  ["lentil", "🫘"],
  ["chana", "🫘"],
  ["rajma", "🫘"],
  ["quinoa", "🌾"],
  ["juice", "🧃"],
  ["water", "💧"],
  ["soda", "🥤"],
  ["cola", "🥤"],
  ["coffee", "☕"],
  ["tea", "🍵"],
  ["beer", "🍺"],
  ["wine", "🍷"],
  ["chips", "🍟"],
  ["namkeen", "🥨"],
  ["popcorn", "🍿"],
  ["chocolate", "🍫"],
  ["candy", "🍬"],
  ["honey", "🍯"],
  ["jam", "🍯"],
  ["ketchup", "🍅"],
  ["sauce", "🥫"],
  ["mayonnaise", "🥫"],
  ["mayo", "🥫"],
  ["pickle", "🥒"],
  ["vinegar", "🧴"],
  ["oil", "🛢️"],
  ["salt", "🧂"],
  ["sugar", "🍬"],
  ["jaggery", "🟤"],
  ["masala", "🌶️"],
  ["turmeric", "🟡"],
  ["cumin", "🌰"],
  ["nut", "🥜"],
  ["almond", "🌰"],
  ["cashew", "🌰"],
  ["raisin", "🍇"],
  ["frozen", "🧊"],
  ["ice", "🧊"],
  ["soup", "🍲"],
  ["tofu", "🧊"],
  ["cereal", "🥣"],
];

const SORTED = [...KEYWORD_EMOJI].sort((a, b) => b[0].length - a[0].length);

/** Emoji that best represents a product name (falls back to its category). */
export function emojiFor(name: string, category?: string): string {
  const n = (name ?? "").toLowerCase();
  for (const [key, emoji] of SORTED) if (n.includes(key)) return emoji;
  return (category && CATEGORY_EMOJI[category]) || CATEGORY_EMOJI.Other;
}

export function categoryEmoji(category: string): string {
  return CATEGORY_EMOJI[category] ?? CATEGORY_EMOJI.Other;
}

const STORAGE_EMOJI: Record<string, string> = {
  Fridge: "\u{1F9CA}",
  Freezer: "\u2744\uFE0F",
  Pantry: "\u{1F5C4}\uFE0F",
};

export function storageEmoji(storage: string): string {
  return STORAGE_EMOJI[storage] ?? STORAGE_EMOJI.Pantry;
}

export { STORAGE_EMOJI };
