/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellShoppingRouteImport } from './routes/_shell.shopping'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellScannerRouteImport } from './routes/_shell.scanner'
import { Route as ShellRecipesRouteImport } from './routes/_shell.recipes'
import { Route as ShellProfileRouteImport } from './routes/_shell.profile'
import { Route as ShellPantryRouteImport } from './routes/_shell.pantry'
import { Route as ShellNotificationsRouteImport } from './routes/_shell.notifications'
import { Route as ShellAssistantRouteImport } from './routes/_shell.assistant'
import { Route as ShellAnalyticsRouteImport } from './routes/_shell.analytics'
import { Route as ShellAdminBarcodesRouteImport } from './routes/_shell.admin-barcodes'
import { Route as ShellAdminRouteImport } from './routes/_shell.admin'
import { Route as ApiPublicPushDigestRouteImport } from './routes/api/public/push-digest'
import { Route as ShellAdminUserUserIdRouteImport } from './routes/_shell.admin-user.$userId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellShoppingRoute = ShellShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellScannerRoute = ShellScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRecipesRoute = ShellRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProfileRoute = ShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPantryRoute = ShellPantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNotificationsRoute = ShellNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAssistantRoute = ShellAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAnalyticsRoute = ShellAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminBarcodesRoute = ShellAdminBarcodesRouteImport.update({
  id: '/admin-barcodes',
  path: '/admin-barcodes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminRoute = ShellAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ShellRoute,
} as any)
const ApiPublicPushDigestRoute = ApiPublicPushDigestRouteImport.update({
  id: '/api/public/push-digest',
  path: '/api/public/push-digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAdminUserUserIdRoute = ShellAdminUserUserIdRouteImport.update({
  id: '/admin-user/$userId',
  path: '/admin-user/$userId',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof ShellAdminRoute
  '/admin-barcodes': typeof ShellAdminBarcodesRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/assistant': typeof ShellAssistantRoute
  '/notifications': typeof ShellNotificationsRoute
  '/pantry': typeof ShellPantryRoute
  '/profile': typeof ShellProfileRoute
  '/recipes': typeof ShellRecipesRoute
  '/scanner': typeof ShellScannerRoute
  '/settings': typeof ShellSettingsRoute
  '/shopping': typeof ShellShoppingRoute
  '/admin-user/$userId': typeof ShellAdminUserUserIdRoute
  '/api/public/push-digest': typeof ApiPublicPushDigestRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof ShellAdminRoute
  '/admin-barcodes': typeof ShellAdminBarcodesRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/assistant': typeof ShellAssistantRoute
  '/notifications': typeof ShellNotificationsRoute
  '/pantry': typeof ShellPantryRoute
  '/profile': typeof ShellProfileRoute
  '/recipes': typeof ShellRecipesRoute
  '/scanner': typeof ShellScannerRoute
  '/settings': typeof ShellSettingsRoute
  '/shopping': typeof ShellShoppingRoute
  '/': typeof ShellIndexRoute
  '/admin-user/$userId': typeof ShellAdminUserUserIdRoute
  '/api/public/push-digest': typeof ApiPublicPushDigestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_shell/admin': typeof ShellAdminRoute
  '/_shell/admin-barcodes': typeof ShellAdminBarcodesRoute
  '/_shell/analytics': typeof ShellAnalyticsRoute
  '/_shell/assistant': typeof ShellAssistantRoute
  '/_shell/notifications': typeof ShellNotificationsRoute
  '/_shell/pantry': typeof ShellPantryRoute
  '/_shell/profile': typeof ShellProfileRoute
  '/_shell/recipes': typeof ShellRecipesRoute
  '/_shell/scanner': typeof ShellScannerRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/shopping': typeof ShellShoppingRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/admin-user/$userId': typeof ShellAdminUserUserIdRoute
  '/api/public/push-digest': typeof ApiPublicPushDigestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/admin-barcodes'
    | '/analytics'
    | '/assistant'
    | '/notifications'
    | '/pantry'
    | '/profile'
    | '/recipes'
    | '/scanner'
    | '/settings'
    | '/shopping'
    | '/admin-user/$userId'
    | '/api/public/push-digest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/admin-barcodes'
    | '/analytics'
    | '/assistant'
    | '/notifications'
    | '/pantry'
    | '/profile'
    | '/recipes'
    | '/scanner'
    | '/settings'
    | '/shopping'
    | '/'
    | '/admin-user/$userId'
    | '/api/public/push-digest'
  id:
    | '__root__'
    | '/_shell'
    | '/auth'
    | '/sitemap.xml'
    | '/_shell/admin'
    | '/_shell/admin-barcodes'
    | '/_shell/analytics'
    | '/_shell/assistant'
    | '/_shell/notifications'
    | '/_shell/pantry'
    | '/_shell/profile'
    | '/_shell/recipes'
    | '/_shell/scanner'
    | '/_shell/settings'
    | '/_shell/shopping'
    | '/_shell/'
    | '/_shell/admin-user/$userId'
    | '/api/public/push-digest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicPushDigestRoute: typeof ApiPublicPushDigestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/shopping': {
      id: '/_shell/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShellShoppingRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/scanner': {
      id: '/_shell/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ShellScannerRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/recipes': {
      id: '/_shell/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof ShellRecipesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/profile': {
      id: '/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShellProfileRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pantry': {
      id: '/_shell/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof ShellPantryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/notifications': {
      id: '/_shell/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ShellNotificationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/assistant': {
      id: '/_shell/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof ShellAssistantRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/analytics': {
      id: '/_shell/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ShellAnalyticsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin-barcodes': {
      id: '/_shell/admin-barcodes'
      path: '/admin-barcodes'
      fullPath: '/admin-barcodes'
      preLoaderRoute: typeof ShellAdminBarcodesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin': {
      id: '/_shell/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ShellAdminRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/public/push-digest': {
      id: '/api/public/push-digest'
      path: '/api/public/push-digest'
      fullPath: '/api/public/push-digest'
      preLoaderRoute: typeof ApiPublicPushDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/admin-user/$userId': {
      id: '/_shell/admin-user/$userId'
      path: '/admin-user/$userId'
      fullPath: '/admin-user/$userId'
      preLoaderRoute: typeof ShellAdminUserUserIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAdminRoute: typeof ShellAdminRoute
  ShellAdminBarcodesRoute: typeof ShellAdminBarcodesRoute
  ShellAnalyticsRoute: typeof ShellAnalyticsRoute
  ShellAssistantRoute: typeof ShellAssistantRoute
  ShellNotificationsRoute: typeof ShellNotificationsRoute
  ShellPantryRoute: typeof ShellPantryRoute
  ShellProfileRoute: typeof ShellProfileRoute
  ShellRecipesRoute: typeof ShellRecipesRoute
  ShellScannerRoute: typeof ShellScannerRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellShoppingRoute: typeof ShellShoppingRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellAdminUserUserIdRoute: typeof ShellAdminUserUserIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAdminRoute: ShellAdminRoute,
  ShellAdminBarcodesRoute: ShellAdminBarcodesRoute,
  ShellAnalyticsRoute: ShellAnalyticsRoute,
  ShellAssistantRoute: ShellAssistantRoute,
  ShellNotificationsRoute: ShellNotificationsRoute,
  ShellPantryRoute: ShellPantryRoute,
  ShellProfileRoute: ShellProfileRoute,
  ShellRecipesRoute: ShellRecipesRoute,
  ShellScannerRoute: ShellScannerRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellShoppingRoute: ShellShoppingRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellAdminUserUserIdRoute: ShellAdminUserUserIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicPushDigestRoute: ApiPublicPushDigestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
